// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRsO-liBH-HCEX6b1ATT5M4fMAE6xSXxk',
    appId: '1:781699518887:web:1908405c45125f56912682',
    messagingSenderId: '781699518887',
    projectId: 'bottled-star',
    authDomain: 'bottled-star.firebaseapp.com',
    storageBucket: 'bottled-star.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPrEj0SUxzRRGpF7b11lks0wVCWJ24xRQ',
    appId: '1:781699518887:android:4a6e07ab99412b48912682',
    messagingSenderId: '781699518887',
    projectId: 'bottled-star',
    storageBucket: 'bottled-star.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1PMobFo1oj-rJS1xNuIAYN9FDugtIWo',
    appId: '1:781699518887:ios:4deed4109ac5bfa8912682',
    messagingSenderId: '781699518887',
    projectId: 'bottled-star',
    storageBucket: 'bottled-star.firebasestorage.app',
    iosBundleId: 'pro.daddoodev.bottledstar',
  );
}
